//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HEAPIFY_540_Software.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AccountsAdmins = new HashSet<AccountsAdmin>();
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.CreateOrderInternals = new HashSet<CreateOrderInternal>();
            this.CreateOrderInternals1 = new HashSet<CreateOrderInternal>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public int AddressID { get; set; }
        public int PhoneNumberID { get; set; }
        public string Position { get; set; }
        public string Department { get; set; }
        public string EmployeeSSN { get; set; }
        public string PersonalEmail { get; set; }
        public System.DateTime EmployeeDateOfBirth { get; set; }
    
        // Added 11/28/2017 -- PLB
        public string FullName
        {
            get
            {
                if (MiddleName == String.Empty)
                {
                    return FirstName + " " + LastName;
                }

                else
                {
                    return FirstName + " " + MiddleName + " " + LastName;
                }
            }
        }

        // Added 11/28/2017 -- PLB
        // Wanted to display only the date
        public string EmployeeDateOfBirthDateOnly
        {
            get
            {
                return EmployeeDateOfBirth.ToShortDateString();
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountsAdmin> AccountsAdmins { get; set; }
        public virtual Address Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreateOrderInternal> CreateOrderInternals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreateOrderInternal> CreateOrderInternals1 { get; set; }
        public virtual PhoneNumber PhoneNumber { get; set; }
    }
}
